# Generated by Django 5.1.8 on 2025-04-08 22:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_group_list_db_updated_by_group_list_db_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_list_db',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 128323)),
        ),
        migrations.AlterField(
            model_name='group_list_db',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 128830)),
        ),
        migrations.AlterField(
            model_name='meeting_notes_db',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 130138)),
        ),
        migrations.AlterField(
            model_name='meeting_notes_db',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 130138)),
        ),
        migrations.AlterField(
            model_name='project_list_db',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 128980)),
        ),
        migrations.AlterField(
            model_name='project_list_db',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 128980)),
        ),
        migrations.CreateModel(
            name='task_list_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('task_title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('task_status', models.TextField(blank=True)),
                ('originator', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 130964))),
                ('created_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 9, 5, 51, 54, 130964))),
                ('updated_by', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.group_list_db')),
                ('meeting_notes_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.meeting_notes_db')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.project_list_db')),
            ],
        ),
    ]
